Add registration view
ryo-kamido/freemarket_sample_45-C pull request #14
Opened 2019-03-03 10:57 UTC by ryo-kamido

# WHAT
ログイン画面の実装
rechptcha_tagsに関してはこの次のコミットにて実装予定。
loginとregistrationを明確にした。
# WHY
同内容のボタンではないため、登録とログインを明確化させるため。
また、recaptchに関してはマージンのみを先に設定し、どこに導入するかのみを決めた

2019-03-03 11:11 UTC, yuki-uchida requested changes

2019-03-03 11:11 UTC, yuki-uchida commented on app/assets/stylesheets/_registration-footer.scss
> +        .agreement{
この辺りもBEMにそう形で記述しましょう

2019-03-03 11:11 UTC, yuki-uchida commented on app/assets/stylesheets/_registration-footer.scss
> +        .tokutei{
ここも

2019-03-04 02:52 UTC, ryo-kamido commented on app/assets/stylesheets/_registration-footer.scss
> +        .agreement{
修正しました

2019-03-04 02:52 UTC, ryo-kamido commented on app/assets/stylesheets/_registration-footer.scss
> +        .tokutei{
修正しました

2019-03-04 02:54 UTC, hzak2xx approved these changes
LGTM

2019-03-04 06:35 UTC, merged