クレジットカード登録画面
ryo-kamido/freemarket_sample_45-C pull request #32
Opened 2019-03-13 10:31 UTC by zerotaisuke

# what
・クレジットカード登録画面のビューを作成。
・各種クレジットロゴは、images/credit_logoに保存してimageタグで取得。
・専用scssファイル（credit1.scss)を作成。

2019-03-13 10:37 UTC, yuki-uchida requested changes

2019-03-13 10:37 UTC, yuki-uchida commented on app/assets/stylesheets/credit1.scss
> +
credit1という名前は不適切です。
1が何を表しているのか分からないためです。
他の名前を検討してください

2019-03-13 10:37 UTC, yuki-uchida commented on app/assets/stylesheets/credit1.scss
> +      display: inline-block;
この辺り、BEMに沿ったクラス名が付けられていません。こちらを参考に、アンバサンドを活用した記述にしてくださいhttps://qiita.com/Takuan_Oishii/items/0f0d2c5dc33a9b2d9cb1

2019-03-13 10:37 UTC, yuki-uchida commented on app/views/profiles/credit1.html.haml
> +              %option{:value => "02"} 02
railsのdate selectで良いのでは？
一度調べてみてください

2019-03-16 08:52 UTC, zerotaisuke commented on app/assets/stylesheets/credit1.scss
> +
registration_creditcard
に変更しました。

2019-03-16 08:53 UTC, zerotaisuke commented on app/assets/stylesheets/credit1.scss
> +      display: inline-block;
アンバサンドを活用した記述に修正しました

2019-03-16 08:55 UTC, zerotaisuke commented on app/views/profiles/credit1.html.haml
> +              %option{:value => "02"} 02
調べました。
今回においてはoptionで進めさせていただけますと幸いです。

2019-03-16 08:56 UTC, zerotaisuke commented
<img width="1440" alt="スクリーンショット 2019-03-16 17 48 31" src="https://user-images.githubusercontent.com/47076525/54472960-b2ee0580-4814-11e9-9e9d-7333615f0a92.png">

2019-03-16 08:58 UTC, zerotaisuke commented
前回プレビュー画面を添付し忘れておりました。大変失礼いたしました。
現状のプレビュイー画面を添付いたします。

2019-03-16 09:07 UTC, yuki-uchida commented on app/views/profiles/credit1.html.haml
> +              %option{:value => "02"} 02
それはなぜですか？

2019-03-16 09:09 UTC, yuki-uchida requested changes

2019-03-16 09:09 UTC, yuki-uchida commented on app/assets/stylesheets/registration_creditcard.scss
> +  .masterlogo{
この辺りも全てBEMに沿ってクラス命名をしてください。
もし様々なところで使われるCSSの場合にはmixinで呼び出す形にしましょう

2019-03-16 11:13 UTC, zerotaisuke commented on app/views/profiles/credit1.html.haml
> +              %option{:value => "02"} 02
いくつかdeta_selectの記事を漁り、年と月をdate_selectで表現することは可能と感じましたが、「http://mooooooooooriiiiii.hatenablog.com/entry/2017/05/15/180405」の記事にて、detaselectで出力される値は、YYYY/MM/01となり、日付の値は強制的に1日が出力されるとのことでした。ここからは、私個人の能力の問題になりますが、この1日という日付が今後、どういう影響を与えられるかの想像がつかない状況です。また、クレジットカードでは、月初の日付ではなく月末まで利用できるものであるため、仮に日付の情報を出力するのであれば、厳密には日付の値は31日にしなければならないとも思えます。
いろいろと言い訳になってしまい恐縮ですが、クレジットカードという情報の重要性から私の能力で確実に表現ができ、正確な情報を受けわたすことができるであろう、oputionの使用が良いと判断した次第です。
以上、ご確認のほどよろしくお願いいたします。

2019-03-16 12:28 UTC, zerotaisuke commented on app/assets/stylesheets/registration_creditcard.scss
> +  .masterlogo{
# what
・ロゴ部分の記述をBEMに沿って命名をしました。
・別途登録されていたmixinの記述を活用して表現するようにしました。
ｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰ
@mixin height_width($height,$width){
  height: $height;
  width:  $width;
}
ｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰｰ
・コメントアウトの記述を行い、メンテナンスしやすくしました。

2019-03-16 12:59 UTC, yuki-uchida requested changes

2019-03-16 12:59 UTC, yuki-uchida commented on app/assets/stylesheets/registration_creditcard.scss
> +.l-chapter-credithead{
この辺りもBEMに沿ってください。全体的に見直してみてください

2019-03-16 13:00 UTC, yuki-uchida commented on app/views/profiles/credit1.html.haml
> +              %option{:value => "02"} 02
かしこまりました一応対策もお伝えしておきますね


日付の部分だけ追加で選択し、送信しRails側で結合すれば良いでしょう。

機嫌もあるため、今回はこのまま行きましょう

2019-03-17 08:09 UTC, zerotaisuke commented on app/assets/stylesheets/registration_creditcard.scss
> +.l-chapter-credithead{
# what
メルカリに合わせていたクラス名をBEM記法に合わせて変更

2019-03-17 08:13 UTC, zerotaisuke commented on app/views/profiles/credit1.html.haml
> +              %option{:value => "02"} 02
恐れ入ります。ありがとうございます。
後日にはなってしまいますが、ご指導いただきました点をはじめさらに理解を深めることができるように努力いたします。

2019-03-17 08:14 UTC, yuki-uchida approved these changes
LGTMです。お疲れ様でした

2019-03-17 08:16 UTC, zerotaisuke commented
ありがとうございました。引き続きご指導のほどよろしくお願いいたします。

2019-03-18 05:20 UTC, merged