Create_Fucntion_of_User_Registration_with_Mail_address(メールアドレスでのユーザー登録機能の作成)
ryo-kamido/freemarket_sample_45-C pull request #7
Opened 2019-03-01 10:53 UTC by Fujiten

# WHAT

- メールアドレスでのユーザーの新規登録機能を追加しました。

## 遷移の流れ　
- 新規登録画面(new_user_registration_path)をクリック

- コントローラー(users/registrations_controller.rb)でインスタンスを用意

```registrations_controller.rb
def new
 build_resource({})   　　   #  => @userの作成 
 resource.build_profile     #  => @profileの作成
end
```

- 新規作成画面にて、@userに@profileをネストさせながらフォームで値を受け取る

- ApplicationControllerでdeviseの用意したストロングパラメータを使用

- User、Profileそれぞれのバリデーションを超えればDBにCOMMITする。

## 単体テストについて

- 適切な必要量がわからなかったので、とりあえずマストなものを記述しています。

## 登録画面

<img width="1440" alt="2019-03-01 19 48 06" src="https://user-images.githubusercontent.com/45753250/53633612-5955da80-3c5b-11e9-9b95-3e83e751b2bb.png">

レビューよろしくお願いいたします！

2019-03-01 11:02 UTC, yuki-uchida requested changes

2019-03-01 11:02 UTC, yuki-uchida commented on app/views/devise/registrations/new.html.haml
> +      %br
brは禁止です。
marginとpaddingでデザインを整えましょう

2019-03-01 11:02 UTC, yuki-uchida commented on spec/factories/profiles.rb
> +    birthdate             {"20000101"}
Fakerを使ってランダム生成しましょう

2019-03-02 05:05 UTC, Fujiten commented on app/views/devise/registrations/new.html.haml
> +      %br
承知しました。brを削除します！
marginなどは後でフロントの作業として追加します！

2019-03-02 05:24 UTC, Fujiten commented on spec/factories/profiles.rb
> +    birthdate             {"20000101"}
Fakerを使用しました。
また、アプリケーションの言語設定を日本語に変更しました！

2019-03-02 05:29 UTC, yuki-uchida requested changes

2019-03-02 05:29 UTC, yuki-uchida commented on app/controllers/users/registrations_controller.rb
> +    build_resource
build_resourceでは少々曖昧です。
なんのresourceをbuildするのかわかるような名前だといいです。

2019-03-02 05:29 UTC, yuki-uchida commented on app/controllers/users/registrations_controller.rb
> +    resource.build_profile
resourceが何を表しているのかわかるようにしましょう。
全てのデータがresourceに当てはまってしまい、解釈が難しくなります。
具体的すぎるくらいの名前がちょうどいいです

2019-03-02 06:06 UTC, Fujiten commented on app/controllers/users/registrations_controller.rb
> +    resource.build_profile
承知しました！　たしかにインスタンスの定義が暗黙的だったので、あとからみて分かりやすいようにコードを変更しました。
よろしくおねがいします。

2019-03-02 06:10 UTC, yuki-uchida approved these changes
LGTMです。お疲れ様でした

2019-03-02 06:11 UTC, Fujiten commented
ありがとうございます！マージします

2019-03-02 06:12 UTC, merged